analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
linter:
  rules:
    - avoid_private_typedef_functions
    - await_only_futures
    - cancel_subscriptions
    - close_sinks
    - unawaited_futures
    - avoid_init_to_null
